# Generated by Django 5.1.1 on 2024-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
