# Generated by Django 5.1.1 on 2024-10-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
