# Generated by Django 5.1.1 on 2024-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employerprofile_address_jobseekerprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
