# Generated by Django 5.1.1 on 2024-11-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employerprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
