# Generated by Django 5.1.1 on 2024-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobseekerprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
