# Generated by Django 5.1.1 on 2024-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('Intern', 'Intern')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Annual', 'Annual')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
