# Generated by Django 5.1.1 on 2024-10-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_application_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='expiry_date',
        ),
    ]
