# Generated by Django 5.1.1 on 2024-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobposting_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Annual', 'Annual'), ('Monthly', 'Monthly')], max_length=100, null=True),
        ),
    ]
