# Generated by Django 5.1.1 on 2024-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobposting_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, default='images/default-logo.png', null=True, upload_to='company_logos/'),
        ),
    ]
