# Generated by Django 5.1.1 on 2024-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobposting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
