# Generated by Django 5.1.1 on 2024-11-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobposting_company_logo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyreview',
            table='company_review',
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='job_application',
        ),
        migrations.AlterModelTable(
            name='savedjob',
            table='saved_job',
        ),
    ]
